import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../app/Components/Header'
import Footer from '../app/Components/Footer'
import Transition from '../app/Components/Transition'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dhairya Gupta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Transition />
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
